from .core import (
    ArrayBackend,
    BackendError,
    BackendManager,
    NumPyBackend,
    Registry,
    TorchBackend,
    backend_manager,
    get_backend,
    set_default_backend,
)
from .mesh import (
    CELL_TYPES,
    HEXA8,
    QUAD4,
    QUAD8,
    QUAD9,
    TETRA4,
    TRIANGLE3,
    TRIANGLE6,
    CellDescriptor,
    Connectivity,
    HexaMesh,
    Mesh,
    MeshData,
    MeshGeometry,
    QuadMesh,
    TetraMesh,
    Topology,
    TriangleMesh,
    get_cell_type,
    register_cell_type,
)
from .meshing import (
    EntityPointManager,
    MeshFactory,
    MeshGenerator,
    MeshGeneratorRegistry,
    MeshRefiner,
    RefinementContext,
    RefinementDataTransfer,
    RefinementRegistry,
    RefinementResult,
    available_refinement_methods,
    mesh_generator_registry,
    refine,
    refinement_registry,
)
from .post import PlotOptions, Viewer, ViewerOptions, plot_mesh

__version__ = "2.1.0"

__all__ = [
    "__version__",
    "ArrayBackend", "NumPyBackend", "TorchBackend",
    "BackendManager", "BackendError", "backend_manager",
    "get_backend", "set_default_backend", "Registry",
    "CellDescriptor", "CELL_TYPES", "register_cell_type",
    "get_cell_type", "TRIANGLE3", "TRIANGLE6", "QUAD4",
    "QUAD8", "QUAD9", "TETRA4", "HEXA8",
    "Connectivity", "MeshData", "MeshGeometry", "Topology",
    "Mesh", "TriangleMesh", "QuadMesh", "TetraMesh", "HexaMesh",
    "MeshFactory", "MeshGenerator", "MeshGeneratorRegistry",
    "mesh_generator_registry", "refine",
    "available_refinement_methods", "MeshRefiner",
    "RefinementContext", "RefinementResult",
    "RefinementRegistry", "refinement_registry",
    "EntityPointManager", "RefinementDataTransfer",
    "PlotOptions", "ViewerOptions", "plot_mesh", "Viewer",
]
